config/routes.rb
Rails.application.routes.draw do
  root 'uploads#index'

  resources :uploads
end

app/models/upload.rb
class Upload < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
  end

  def create
    # Make an object in your bucket for your upload
    p BUCKET
    p params[:file]
    p params[:file].original_filename

    file_data = params[:file]
    if file_data.respond_to?(:read)
      contents = file_data.read
    elsif file_data.respond_to?(:path)
      contents = File.read(file_data.path)
    else
      logger.error "Bad file_data: #{file_data.class.name}: #{file_data.inspect}"
      flash.now[:notice] = 'Uploaded file was corrupted somewhere in transit'
      render :new
      return
    end

    s3_file = BUCKET.files.new(
      key: params[:file].original_filename,
      body: file_data,
      public: true
    )

    if s3_file.save
      p s3_file

      # Create model object for the upload
      @upload = Upload.new(
        url: s3_file.public_url,
        name: s3_file.key
      )

      # Save the upload
      if @upload.save
        redirect_to uploads_path, success: 'File successfully uploaded'
      else
        flash.now[:notice] = 'There was an error updating database'
        render :new
      end
    else
      flash.now[:notice] = 'There was an error uploading file to object store'
      render :new
    end
  end

  def index
    @uploads = Upload.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails app to upload files to AWS S3 on Cloud Foundry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/uploads/create.html.erb
<h1>Uploads#create</h1>
<p>Find me in app/views/uploads/create.html.erb</p>

app/views/uploads/index.html.erb
<h1>All uploads</h1>
<%= link_to "New upload", new_upload_path %>
<% @uploads.each do |upload| %>
    <div>
        <%= link_to upload.name, upload.url %>
    </div>
<% end %>

app/views/uploads/new.html.erb
<h1>Upload a file</h1>

<%= form_tag uploads_path, enctype: 'multipart/form-data' do %>
    <%= file_field_tag :file  %>
    <%= submit_tag 'Upload file' %>
<% end %>